# Generated by Django 4.1.6 on 2023-05-22 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pojisteni',
            options={'verbose_name': 'Pojisteni'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'uzivatele_pojisteni'},
        ),
        migrations.RenameField(
            model_name='pojisteni',
            old_name='cestovni',
            new_name='typy_pojisteni',
        ),
        migrations.RemoveField(
            model_name='pojisteni',
            name='havarijni',
        ),
        migrations.RemoveField(
            model_name='pojisteni',
            name='zakladni',
        ),
    ]
