# Generated by Django 4.1.6 on 2023-05-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0002_alter_pojisteni_options_alter_users_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojisteni',
            name='pojistenci',
            field=models.ManyToManyField(blank=True, to='insurance_app.users'),
        ),
    ]
