# Generated by Django 4.1.6 on 2023-05-23 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0005_alter_users_address_alter_users_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pojisteni',
            name='pojistenci',
        ),
    ]
