# Generated by Django 4.1.6 on 2023-05-23 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0006_remove_pojisteni_pojistenci'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pojisteni',
        ),
    ]
