# Generated by Django 4.1.6 on 2023-05-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0007_delete_pojisteni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pojisteni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ_pojisteni', models.CharField(max_length=120)),
                ('amount', models.CharField(max_length=120)),
                ('item', models.CharField(max_length=120)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('attendees', models.ManyToManyField(blank=True, to='insurance_app.users')),
            ],
            options={
                'verbose_name': 'pojisteni',
            },
        ),
    ]
