# Generated by Django 4.1.6 on 2023-05-23 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0008_pojisteni'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pojisteni',
            options={},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
        migrations.RenameField(
            model_name='pojisteni',
            old_name='typ_pojisteni',
            new_name='cover',
        ),
    ]
