# Generated by Django 4.1.6 on 2023-05-23 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0009_alter_pojisteni_options_alter_users_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pojisteni',
            name='attendees',
        ),
    ]
