# Generated by Django 4.1.6 on 2023-05-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0010_remove_pojisteni_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='pojisteni',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
