# Generated by Django 4.1.6 on 2023-05-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0011_users_pojisteni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='pojisteni',
        ),
        migrations.AddField(
            model_name='users',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='insurance_app.pojisteni'),
        ),
    ]
