# Generated by Django 4.1.6 on 2023-05-24 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0013_rename_attendees_users_pojisteni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produkty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.CharField(max_length=120)),
                ('notes', models.CharField(max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='pojisteni',
        ),
    ]
