# Generated by Django 4.1.6 on 2023-05-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0014_produkty_remove_users_pojisteni'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='insurance_app.pojisteni'),
        ),
    ]
