# Generated by Django 4.1.6 on 2023-05-25 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0016_rename_attendees_users_pojisteni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='pojisteni',
            new_name='pridat_pojisteni',
        ),
    ]
