# Generated by Django 4.1.6 on 2023-05-25 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0017_rename_pojisteni_users_pridat_pojisteni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkty',
            name='notes',
        ),
    ]
