# Generated by Django 4.1.6 on 2023-05-25 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0019_remove_users_pridat_pojisteni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pojisteni',
            name='item',
        ),
    ]
