# Generated by Django 4.1.6 on 2023-05-25 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0020_remove_pojisteni_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pojisteni',
            name='cover',
        ),
    ]
