# Generated by Django 4.1.6 on 2023-05-25 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0021_remove_pojisteni_cover'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pojisteni',
        ),
        migrations.DeleteModel(
            name='Produkty',
        ),
    ]
