# Generated by Django 4.1.6 on 2023-05-25 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0023_product_pojisteni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pojisteni',
            name='name',
        ),
    ]
