# Generated by Django 4.1.6 on 2023-05-25 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0024_remove_pojisteni_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
    ]
