# Generated by Django 4.1.6 on 2023-05-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0025_rename_name_product_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='insurance_app.pojisteni'),
        ),
    ]
