# Generated by Django 4.1.6 on 2023-05-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0026_users_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='produkt',
            field=models.ManyToManyField(blank=True, to='insurance_app.product'),
        ),
    ]
