# Generated by Django 4.1.6 on 2023-05-25 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0028_rename_attendees_users_doba_pojisteni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pojisteni',
            old_name='pojisteni',
            new_name='typ_pojisteni',
        ),
    ]
