# Generated by Django 4.1.6 on 2023-05-25 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0029_rename_pojisteni_pojisteni_typ_pojisteni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='produkt',
        ),
    ]
