# Generated by Django 4.1.6 on 2023-06-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0030_remove_users_produkt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='doba_pojisteni',
        ),
        migrations.AddField(
            model_name='users',
            name='sjednane',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
