# Generated by Django 4.1.6 on 2023-06-05 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0031_remove_users_doba_pojisteni_users_sjednane'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='sjednane',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_app.product'),
        ),
    ]
