# Generated by Django 4.1.6 on 2023-06-05 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0033_alter_users_sjednane'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pojisteni',
            old_name='typ_pojisteni',
            new_name='product',
        ),
    ]
