# Generated by Django 4.1.6 on 2023-06-06 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0039_test_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='pojisteni_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_app.pojisteni'),
        ),
    ]
