# Generated by Django 4.1.6 on 2023-06-06 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0040_test_pojisteni_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='sjednane',
        ),
        migrations.AddField(
            model_name='test',
            name='users_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_app.users'),
        ),
    ]
