# Generated by Django 4.1.6 on 2023-06-06 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0042_remove_test_test_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='pojisteni_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_app.pojisteni'),
        ),
        migrations.AddField(
            model_name='users',
            name='sjednane',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_app.product'),
        ),
    ]
