# Generated by Django 4.1.6 on 2023-06-06 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0043_users_pojisteni_name_users_sjednane'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='sjednane',
            new_name='produkt',
        ),
    ]
