# Generated by Django 4.1.6 on 2023-06-06 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0044_rename_sjednane_users_produkt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='pojisteni_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='produkt',
        ),
    ]
