# Generated by Django 4.1.6 on 2023-06-06 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0045_remove_users_pojisteni_name_remove_users_produkt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
