# Generated by Django 4.1.6 on 2023-06-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0048_remove_users_product_users_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='contract',
        ),
        migrations.AddField(
            model_name='users',
            name='contract',
            field=models.ManyToManyField(blank=True, null=True, to='insurance_app.pojisteni'),
        ),
    ]
