# Generated by Django 4.1.6 on 2023-06-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0053_remove_users_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='pojisteni',
        ),
        migrations.AddField(
            model_name='users',
            name='pojisteni',
            field=models.ManyToManyField(blank=True, null=True, to='insurance_app.pojisteni'),
        ),
    ]
