# Generated by Django 4.1.6 on 2023-06-07 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0054_remove_users_pojisteni_users_pojisteni'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pojisteni',
            new_name='Contract',
        ),
    ]
