# Generated by Django 4.1.6 on 2023-06-07 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0055_rename_pojisteni_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='pojisteni',
        ),
        migrations.AddField(
            model_name='users',
            name='pojisteni',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_app.contract'),
        ),
    ]
