# Generated by Django 4.1.6 on 2023-06-07 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0056_remove_users_pojisteni_users_pojisteni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='pojisteni',
            new_name='contract',
        ),
    ]
