# Generated by Django 4.1.6 on 2023-06-08 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0060_remove_users_contract_users_contract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='contract',
            new_name='signed_contract',
        ),
    ]
