# Generated by Django 4.1.6 on 2023-06-08 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0061_rename_contract_users_signed_contract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='signed_contract',
            new_name='attendees',
        ),
    ]
