# Generated by Django 4.1.6 on 2023-06-08 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0062_rename_signed_contract_users_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='attendees',
        ),
        migrations.AddField(
            model_name='users',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_app.contract'),
        ),
    ]
