# Generated by Django 4.1.6 on 2023-06-08 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0064_remove_users_contract_users_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='contract',
        ),
        migrations.AddField(
            model_name='users',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_app.contract'),
        ),
    ]
