# Generated by Django 4.1.6 on 2023-06-08 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0072_remove_users_contract_users_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='contract',
        ),
        migrations.CreateModel(
            name='UsersContracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sjednane', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_app.contract')),
                ('uzivatel', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_app.users')),
            ],
        ),
    ]
