# Generated by Django 4.1.6 on 2023-06-08 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0073_remove_users_contract_userscontracts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersContracts',
            new_name='UserContract',
        ),
    ]
