# Generated by Django 4.1.6 on 2023-06-08 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0081_remove_usercontract_sjednane_usercontract_sjednane'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_app.contract'),
        ),
    ]
