# Generated by Django 4.1.6 on 2023-06-08 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0082_users_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_app.product'),
        ),
    ]
