# Generated by Django 4.1.6 on 2023-06-08 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0084_rename_contract_users_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='new_smlouva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_app.contract'),
        ),
    ]
