# Generated by Django 4.1.6 on 2023-06-08 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0085_users_new_smlouva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='product',
        ),
    ]
