# Generated by Django 4.1.6 on 2023-06-08 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0086_remove_users_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserContract',
        ),
    ]
