# Generated by Django 4.1.6 on 2023-06-08 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0087_delete_usercontract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='new_smlouva',
            new_name='smlouva',
        ),
    ]
