# Generated by Django 4.1.6 on 2023-06-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0088_rename_new_smlouva_users_smlouva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='smlouva',
        ),
        migrations.AddField(
            model_name='users',
            name='smlouva',
            field=models.ManyToManyField(blank=True, null=True, to='insurance_app.contract'),
        ),
    ]
