# Generated by Django 4.1.6 on 2023-06-08 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0089_remove_users_smlouva_users_smlouva'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'SHIT'},
        ),
    ]
