# Generated by Django 4.1.6 on 2023-06-08 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0090_alter_contract_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Sjednana pojisteni'},
        ),
    ]
