# Generated by Django 4.1.6 on 2023-06-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0091_alter_contract_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllContracts',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'contract',
                'managed': False,
            },
        ),
    ]
