# Generated by Django 4.1.6 on 2023-06-12 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0092_allcontracts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allcontracts',
            options={},
        ),
    ]
