# Generated by Django 4.1.6 on 2023-06-12 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0093_alter_allcontracts_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllContracts',
        ),
    ]
