# Generated by Django 4.1.6 on 2023-06-12 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0094_delete_allcontracts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={},
        ),
    ]
